// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuFn19DWNpFRxDH1oZQ3SG3bpvxa8O8C4',
    appId: '1:144934218340:web:484a00f7210baea88c8d71',
    messagingSenderId: '144934218340',
    projectId: 'hospital-flow-app',
    authDomain: 'hospital-flow-app.firebaseapp.com',
    storageBucket: 'hospital-flow-app.firebasestorage.app',
    measurementId: 'G-BQYK665VP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlACvucmY6litHjEAn16G-TMUpD6irv0g',
    appId: '1:144934218340:android:24a224e7af4f92608c8d71',
    messagingSenderId: '144934218340',
    projectId: 'hospital-flow-app',
    storageBucket: 'hospital-flow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD-q0InoHaT6xHdUL5yKdFeqLx8VC773s',
    appId: '1:144934218340:ios:22534e49571067948c8d71',
    messagingSenderId: '144934218340',
    projectId: 'hospital-flow-app',
    storageBucket: 'hospital-flow-app.firebasestorage.app',
    iosBundleId: 'com.example.hospitalFlowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD-q0InoHaT6xHdUL5yKdFeqLx8VC773s',
    appId: '1:144934218340:ios:22534e49571067948c8d71',
    messagingSenderId: '144934218340',
    projectId: 'hospital-flow-app',
    storageBucket: 'hospital-flow-app.firebasestorage.app',
    iosBundleId: 'com.example.hospitalFlowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuFn19DWNpFRxDH1oZQ3SG3bpvxa8O8C4',
    appId: '1:144934218340:web:c1883577e0ad72ea8c8d71',
    messagingSenderId: '144934218340',
    projectId: 'hospital-flow-app',
    authDomain: 'hospital-flow-app.firebaseapp.com',
    storageBucket: 'hospital-flow-app.firebasestorage.app',
    measurementId: 'G-XJTPLB0WWK',
  );
}
